### ISSUE TITLE
各アクターのnavbar.phpの不要箇所

### ISSUE THREAD

**Issue by keisukekesuike** [pieni-php/reservebox-dev#11]
views/a/navbar.phpにおいて、以下の文が使用されることはない

`<?php if (!isset($_SESSION['auth']['a'])): ?>`

以上。
またこれは、その他の「views/アクター/navbar.php」においても同様。

**Comment by kentasaito** [comment]
https://github.com/pieni-php/reservebox-dev/commit/72fdb26ecb0b190058586fe2a38028e7d747f6a0
